import { createHash } from "node:crypto"
import { existsSync } from "node:fs"
import { mkdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import { ensureVenv } from "../src/runtime"

export const FIXTURE_DIR = path.join(import.meta.dir, ".fixtures")

const GEN_SCRIPT = path.join(import.meta.dir, "..", "src", "python", "gen_fixtures.py")
const GEN_HASH_MARKER = path.join(FIXTURE_DIR, ".gen-hash")

async function genScriptHash(): Promise<string> {
  return createHash("sha256").update(await readFile(GEN_SCRIPT)).digest("hex")
}

// Fixtures are regenerated when gen_fixtures.py's own bytes change (not just when swap.png is
// missing) — a sentinel-file check couldn't tell a stale `.fixtures/` dir (generated by an
// older version of the script) from a current one, silently masking edits to the fixtures
// themselves (e.g. a new hyperlink/shape added to a fixture-generating function).
export async function ensureFixtures(): Promise<void> {
  const currentHash = await genScriptHash()
  if (existsSync(path.join(FIXTURE_DIR, "swap.png")) && existsSync(GEN_HASH_MARKER) && (await readFile(GEN_HASH_MARKER, "utf8")) === currentHash) {
    return
  }
  const python = await ensureVenv()
  const proc = Bun.spawn([python, GEN_SCRIPT, FIXTURE_DIR], { stdout: "pipe", stderr: "pipe" })
  if ((await proc.exited) !== 0) {
    throw new Error(`fixture generation failed: ${await new Response(proc.stderr).text()}`)
  }
  await mkdir(FIXTURE_DIR, { recursive: true })
  await writeFile(GEN_HASH_MARKER, currentHash)
}
